version = "3.11.5"
runner.dialect = scala3

maxColumn = 100
align.preset = none
docstrings.style = Asterisk
newlines.beforeCurlyLambdaParams = multilineWithCaseOnly
rewrite.rules = [RedundantBraces, RedundantParens, SortModifiers]
